version: '2'


services :

  osciweb :
    image : ocsinventory/ocsinventory-docker-image
    environment :
      OCS_DBNAME : ocsweb
      OCS_DBUSER : ocs
      OCS_DBPASS : ocs
      OCS_DBSERVER_READ : ocsidb
      OCS_DBSERVER_WRITE : ocsidb
    volumes :
      - ocsdownload:/usr/share/ocsinventory-reports/ocsreports/download/
      - ocssrv:/etc/ocsinventory-reports/
      - ocslib:/var/lib/ocsinventory-reports/
    links :
      - ocsidb
    ports :
      - 8080:80

  ocsidb :
    image : mysql
    environment:
      MYSQL_ROOT_PASSWORD : ocsidbpassword
      MYSQL_DATABASE : ocsweb
      MYSQL_USER : ocs
      MYSQL_PASSWORD : ocs
    volumes :
      - ./sql/:/docker-entrypoint-initdb.d/
      - ocsdata:/var/lib/mysql

  glpi:
    image: diouxx/glpi
    links :
      - mysql
    ports:
      - 80:80

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD : glpidbpassword
      MYSQL_DATABASE : glpidb
      MYSQL_USER : glpi_user
      MYSQL_PASSWORD : glpi
    volumes :
      - glpidata:/var/lib/mysql

  jupyter:
    image: mnagaku/lc-minimal-notebook
    ports:
      - 8888:8888
    volumes:
      - notebooks:/home/jovyan/notebooks


volumes:
  ocsdata:
    driver: local
  ocssrv:
    driver: local
  ocslib:
    driver: local
  ocsdownload:
    driver: local
  glpidata:
    driver: local
  notebooks:
    driver: local
